const FETCH_UNITS = "FETCH_UNITS";
const FETCH_UNITS_SAGA = "FETCH_UNITS_SAGA";
const UPDATE_AGE = "UPDATE_AGE";
const UPDATE_AGE_SAGA = "UPDATE_AGE_SAGA";
const UPDATE_PAGE_TITLE_SAGA = "UPDATE_PAGE_TITLE_SAGA";
const UPDATE_PAGE_TITLE = "UPDATE_PAGE_TITLE";
const UPDATE_SWITCH_SAGA = "UPDATE_SWITCH_SAGA";
const UPDATE_SWITCH = "UPDATE_SWITCH";
const UPDATE_SLIDER_COMMITTED_SAGA = "UPDATE_SLIDER_COMMITTED_SAGA";
const UPDATE_SLIDER_COMMITTED = "UPDATE_SLIDER_COMMITTED";
const UPDATE_SLIDER_SAGA = "UPDATE_SLIDER_SAGA";
const UPDATE_SLIDER = "UPDATE_SLIDER";
const UPDATE_UNITS = "UPDATE_UNITS";
const UPDATE_FILTERED_UNITS = "UPDATE_FILTERED_UNITS";

const TYPES = {
  FETCH_UNITS,
  FETCH_UNITS_SAGA,
  UPDATE_AGE_SAGA,
  UPDATE_AGE,
  UPDATE_PAGE_TITLE_SAGA,
  UPDATE_PAGE_TITLE,
  UPDATE_SWITCH_SAGA,
  UPDATE_SWITCH,
  UPDATE_SLIDER_COMMITTED_SAGA,
  UPDATE_SLIDER_COMMITTED,
  UPDATE_SLIDER_SAGA,
  UPDATE_SLIDER,
  UPDATE_UNITS,
  UPDATE_FILTERED_UNITS,
};

export default TYPES;
